export const userCreateObj = {
  name: "",
  email: "",
  password: "",
  father_name: "",
  family_name: "",
  rule: [],
};
export const regionCreateObj = {
  name_en: "",
  name_ar: "",
};
export const fieldSurveyObj = {
  tourism_License_number: [],
  location: { longitude: "", latitude: "" },
  remarks: "",
  inspectorRelation: [],
  facility_working: [],
  specified_period: [],
  update_method: [],
  license_valid: [],
  reasonOpt: [],
  operator_name: "",
  operator_id: "",
  trade_name: "",
  registration_image: [],
  registration_no: "",
  Facility_Mobile_number: "",
  facility_number: "",
  facility_email: "",
  facility_room_number: "",
  not_renewing_the_license: "",
  facility_not_working_file: [],
  commercial_name_file: "",
  Reasons_for_not_notifying: "",
  building_showing_the_sign: [],
  Tourist_license_copy: [],
  Municipal_license_picture: [],
  the_civil_defense_license_picture: [],
  violation_item: [],
};
export const siteCreateObj = {
  licenseNumber: "",
  licienceType: "",
  issueDate: new Date(),
  startDate: new Date(),
  endDate: new Date(),
  ownerIdentity: "",
  ownerName: "",
  operatorIdentity: "",
  operatorNameAr: "",
  operatorNameEn: "",
  CRNumber: "",
  latitude: "",
  longitude: "",
  buildingNumber: "",
  streetNameAr: "",
  districtAreaAr: "",
  POBox: "",
  mobile: "",
  phone: "",
  email: "",
  facilityTypeEn: "",
  facilityTypeAr: "",
  classificationAr: "",
  classificationEn: "",
  regionId: "",
  cityId: "",
};
