export const userCreateObj = {
  name: "",
  email: "",
  password: "",
  father_name: "",
  family_name: "",
  rule: [],
};
export const regionCreateObj = {
  name_en: "",
  name_ar: "",
};
export const fieldSurveyObj = {
  region: "",
  city: "",
  neighborhood: "",
  street: "",
  tourism_License_number: "",
  location: { longitude: "", latitude: "" },
  remarks: "",
  inspectorRelation: true,
  facility_working: true,
  specified_period: false,
  update_method: false,
  license_valid: true,
  is_violation: false,
  reasonOpt: [],
  operator_name: "",
  operator_id: "",
  trade_name: "",
  registration_image: "",
  registration_no: "",
  Facility_Mobile_number: "",
  facility_number: "",
  facility_email: "",
  facility_room_number: "",
  not_renewing_the_license: "",
  commercial_name_file: "",
};
